---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-pythonic
  annotations:
    render.crossplane.io/runtime: Development
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-pythonic:v0.1.5
#   runtimeConfigRef:
#     name: debug
# ---
# apiVersion: pkg.crossplane.io/v1beta1
# kind: DeploymentRuntimeConfig
# metadata:
#   name: debug
# spec:
#   deploymentTemplate:
#     spec:
#       selector: {}
#       template:
#         spec:
#           containers:
#           - name: package-runtime
#             args:
#             - --debug
